### ISSUE TITLE
Support preprocessor directives

### ISSUE THREAD

**Issue by stadelmanma** [stadelmanma/tree-sitter-fortran#15]
Given that fortran and C both use the same preprocessor I can probably copy these over directly without too many changes.

**Comment by stadelmanma** [comment]
One thing to keep in mind for testing is how preprocessor directives in terrible locations are handled such as tweaking the call signature of a subroutine. I belive this is supported in the C grammar but I'm not sure if that method will work for me.

**Comment by DavidAnderegg** [comment]
What is going on with this? I would highly value this feature as I am working on a project that is littered with directives.

I am also willing to implement this feature myself. But i would probably need some guidance...

What do you think?

**Comment by ZedThree** [comment]
It's been awhile since I looked at this, but I think it's is going to be quite tricky. If you look at how the C grammar implements preprocessor directives, they can appear anywhere and have anything as child nodes. For C this isn't much of a problem because there's not many top-level nodes, but with Fortran there's lots of potential kinds of child nodes.

I'd probably start with some of the standalone directives like `#define`, `#line`. Actually, it would be especially useful to have the directives that come from preprocessed source: `# <line number> <filename>`. This would allow running the preprocessor and then parsing the result at least.

**Comment by stadelmanma** [comment]
@ZedThree yeah it’s a tricky problem since you can do literally anything with preprocessor directives.

**Comment by DavidAnderegg** [comment]
Alright, thanks for your responses.

I think i will fork it, create a PR and start working on the easy directives like `#if` etc. first. Then we will see where this is going.
